<?php use MediaPitch\Core\Csrf; $s=$settings??[]; $profiles=$profiles??[]; $activeMarketplace=$activeMarketplace??($s['marketplace']??''); $isNewProfile=!empty($isNewProfile); ?>
<div class="page-actions"><div><p>Configure optional Amazon Creators API access. Each marketplace keeps its own Partner Tag and credentials; manual CMS features continue working independently.</p></div><div class="inline-actions"><a class="secondary-button" href="<?= e(url('admin/settings/amazon?new=1')) ?>">+ Add marketplace</a><a class="primary-button" href="<?= e(url('admin/settings/amazon/import')) ?>">Search & import products</a></div></div>

<section class="panel"><div class="panel-head"><div><h2>Marketplace profiles</h2><p>The active profile is used for interactive search/import. Scheduled refresh can process every enabled profile.</p></div></div>
<?php if(!$profiles):?><p class="empty">No marketplace profiles yet.</p><?php else:?><div class="table-wrap"><table class="data-table"><thead><tr><th>Marketplace</th><th>Status</th><th>Credentials</th><th>Last success</th><th>Actions</th></tr></thead><tbody>
<?php foreach($profiles as $profile): $market=(string)$profile['marketplace']; $active=!empty($profile['active_profile']); ?>
<tr><td><strong><?= e($market) ?></strong><?php if($active):?> <span class="badge">Active</span><?php endif;?></td><td><?= !empty($profile['enabled'])?'Enabled':'Disabled' ?></td><td><?= !empty($profile['credentials_configured'])?'Configured':'Incomplete' ?></td><td><?= e($profile['last_success']?:'Never') ?></td><td><div class="inline-actions"><a class="secondary-button" href="<?= e(url('admin/settings/amazon?marketplace='.rawurlencode($market))) ?>">Edit</a><?php if(!$active):?><form method="post" action="<?= e(url('admin/settings/amazon/activate')) ?>"><?= Csrf::field() ?><input type="hidden" name="marketplace" value="<?= e($market) ?>"><button class="secondary-button">Activate</button></form><?php endif;?><?php if(count($profiles)>1):?><form method="post" action="<?= e(url('admin/settings/amazon/delete-profile')) ?>" onsubmit="return confirm('Delete the <?= e($market) ?> Amazon profile? Imported products will remain in the catalog.')"><?= Csrf::field() ?><input type="hidden" name="marketplace" value="<?= e($market) ?>"><button class="link-button" style="color:#b91c1c">Delete</button></form><?php endif;?></div></td></tr>
<?php endforeach;?></tbody></table></div><?php endif;?>
</section>

<form method="post" action="<?= e(url('admin/settings/amazon/save')) ?>" class="panel form-panel">
<div class="panel-head"><div><h2><?= $isNewProfile?'Add Amazon marketplace':'Edit '.e((string)($s['marketplace']??$activeMarketplace)) ?></h2><p>Saving this profile also makes it the active profile.</p></div></div>
<?= Csrf::field() ?>
<div class="form-grid">
<label class="check span-2"><input type="checkbox" name="enabled" value="1" <?= !empty($s['enabled'])?'checked':'' ?>> Enable this Creators API marketplace profile</label>
<label>Marketplace<input name="marketplace" required value="<?= e($s['marketplace']??'') ?>" placeholder="www.amazon.in" <?= !$isNewProfile&&!empty($s['marketplace'])?'readonly':'' ?>><small>Amazon marketplace hostname, for example www.amazon.in or www.amazon.com.</small></label>
<label>Associate / Partner tag<input name="partner_tag" value="<?= e($s['partner_tag']??'') ?>"></label>
<label>Credential version<select name="credential_version"><option value="3.2" <?= ($s['credential_version']??'3.2')==='3.2'?'selected':'' ?>>3.2 — EU/India (Login with Amazon)</option><option value="3.1" <?= ($s['credential_version']??'')==='3.1'?'selected':'' ?>>3.1 — North America</option><option value="3.3" <?= ($s['credential_version']??'')==='3.3'?'selected':'' ?>>3.3 — Far East</option><option value="2.2" <?= ($s['credential_version']??'')==='2.2'?'selected':'' ?>>2.2 — EU/India legacy Cognito</option><option value="2.1" <?= ($s['credential_version']??'')==='2.1'?'selected':'' ?>>2.1 — North America legacy Cognito</option><option value="2.3" <?= ($s['credential_version']??'')==='2.3'?'selected':'' ?>>2.3 — Far East legacy Cognito</option></select></label>
<label>Credential ID<input name="credential_id" autocomplete="off" value="<?= e($s['credential_id']??'') ?>" placeholder="Leave blank to keep existing ID"></label>
<label>Credential secret<input type="password" name="credential_secret" autocomplete="new-password" placeholder="Leave blank to keep existing secret"></label>
</div>
<div class="form-actions"><a class="secondary-button" href="<?= e(url('admin/settings/amazon')) ?>">Cancel</a><button class="primary-button">Save & activate profile</button></div>
</form>

<div class="panel" style="margin-top:1rem"><h3>Connection & sync — <?= e($activeMarketplace) ?></h3><p>These actions always use the currently active profile.</p><p><strong>Last successful Amazon request:</strong> <?= e(($activeMarketplace===($s['marketplace']??'')?$s['last_success']:'')?:'See profile table') ?></p><?php if($activeMarketplace===($s['marketplace']??'')&&!empty($s['last_error'])):?><p class="flash error"><strong>Last error:</strong> <?= e($s['last_error']) ?></p><?php endif;?><div class="form-actions" style="justify-content:flex-start;flex-wrap:wrap"><form method="post" action="<?= e(url('admin/settings/amazon/test')) ?>"><?= Csrf::field() ?><button class="secondary-button">Test active profile</button></form><a class="primary-button" href="<?= e(url('admin/settings/amazon/import')) ?>">Search & import products</a><form method="post" action="<?= e(url('admin/settings/amazon/refresh')) ?>" onsubmit="return confirm('Refresh up to 50 stale products for the active marketplace now?')"><?= Csrf::field() ?><button class="secondary-button">Refresh active marketplace</button></form></div><p><small>Manual refresh selects imported/hybrid products whose stored marketplace matches the active profile. Requests are batched and retry transient Amazon errors automatically.</small></p></div>
<div class="panel" style="margin-top:1rem"><h3>Security & freshness</h3><p>All marketplace profiles are stored as one encrypted settings payload using <code>APP_KEY</code>. The active profile is mirrored into the legacy single-profile keys for rollback compatibility. OAuth tokens stay server-side and are fingerprinted by credential version + ID.</p></div>
