<?php
$products=$results['products']??[];$categories=$results['categories']??[];$guides=$results['guides']??[];$comparisons=$results['comparisons']??[];$articles=$results['articles']??[];$reviews=$results['reviews']??[];
$total=count($products)+count($categories)+count($guides)+count($comparisons)+count($articles)+count($reviews);
?>
<section class="section section-soft"><div class="container narrow"><span class="eyebrow">Search</span><h1><?= $query!==''?'Results for “'.e($query).'”':'Find products and advice' ?></h1><form class="hero-search" action="/search" method="get"><input type="search" name="q" value="<?= e($query) ?>" placeholder="Product, category, guide or topic"><button type="submit">Search</button></form></div></section>
<section class="section"><div class="container">
<?php if($query===''):?><div class="empty-state"><p>Enter a product, category, guide or topic to start searching.</p></div>
<?php elseif($total===0):?><div class="empty-state"><h2>No results found</h2><p>Try a broader term.</p></div>
<?php else:?>
<?php if($categories):?><div class="section-head"><div><span class="eyebrow">Browse</span><h2>Categories</h2></div></div><div class="category-grid"><?php foreach($categories as $category):?><a class="category-card" href="<?= e(url('category/'.$category['slug'])) ?>"><span><?= e($category['name']) ?></span><small><?= e($category['description']?:'Explore recommendations') ?></small></a><?php endforeach;?></div><?php endif;?>
<?php if($products):?><div class="section-head" style="margin-top:2rem"><div><span class="eyebrow">Products</span><h2>Matching products</h2></div></div><div class="product-grid"><?php foreach($products as $product):?><article class="product-card"><a class="product-image" href="<?= e(url('product/'.$product['slug'])) ?>"><?php if(!empty($product['main_image_url'])):?><img src="<?= e($product['main_image_url']) ?>" alt="<?= e($product['display_title']?:$product['title']) ?>" loading="lazy"><?php else:?><span class="image-placeholder">Product image</span><?php endif;?></a><div class="card-body"><?php if(!empty($product['best_for_label'])):?><span class="badge"><?= e($product['best_for_label']) ?></span><?php endif;?><h3><a href="<?= e(url('product/'.$product['slug'])) ?>"><?= e($product['display_title']?:$product['title']) ?></a></h3><?php if($product['custom_score']!==null):?><div class="score">MediaPitch score <strong><?= e((string)$product['custom_score']) ?>/10</strong></div><?php endif;?><a class="button button-secondary" href="<?= e(url('product/'.$product['slug'])) ?>">View product</a></div></article><?php endforeach;?></div><?php endif;?>
<?php $contentGroups=[['title'=>'Buying guides','items'=>$guides,'route'=>'guide'],['title'=>'Comparisons','items'=>$comparisons,'route'=>'compare'],['title'=>'Articles','items'=>$articles,'route'=>'blog']]; foreach($contentGroups as $group): if(empty($group['items']))continue;?><div class="section-head" style="margin-top:2rem"><div><h2><?= e($group['title']) ?></h2></div></div><div class="article-grid"><?php foreach($group['items'] as $item):?><article class="article-card"><?php if(!empty($item['featured_image_url'])):?><img src="<?= e($item['featured_image_url']) ?>" alt="" loading="lazy"><?php endif;?><div class="card-body"><h3><a href="<?= e(url($group['route'].'/'.$item['slug'])) ?>"><?= e($item['title']) ?></a></h3><p><?= e($item['excerpt']??'') ?></p></div></article><?php endforeach;?></div><?php endforeach;?>
<?php endif;?>
</div></section>