CREATE TABLE IF NOT EXISTS sender_email_queue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    template_id VARCHAR(100) NOT NULL,
    template_title VARCHAR(255) NULL,
    recipient_email VARCHAR(190) NOT NULL,
    recipient_name VARCHAR(190) NULL,
    variables_json LONGTEXT NULL,
    consent_confirmed TINYINT(1) NOT NULL DEFAULT 0,
    validation_status VARCHAR(20) NULL,
    validation_reason VARCHAR(255) NULL,
    validation_checked_at DATETIME NULL,
    status ENUM('queued','processing','sent','blocked','failed') NOT NULL DEFAULT 'queued',
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME NULL,
    provider_message_id VARCHAR(191) NULL,
    last_error VARCHAR(500) NULL,
    sent_at DATETIME NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_sender_queue_ready (status, next_attempt_at, id),
    KEY idx_sender_queue_sent (sent_at),
    KEY idx_sender_queue_recipient (recipient_email),
    KEY idx_sender_queue_template (template_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
