CREATE TABLE IF NOT EXISTS sender_campaign_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source_campaign_id VARCHAR(100) NOT NULL,
    source_title VARCHAR(255) NULL,
    subject VARCHAR(255) NOT NULL,
    preheader VARCHAR(255) NULL,
    from_name VARCHAR(190) NOT NULL,
    reply_to VARCHAR(190) NOT NULL,
    content_type VARCHAR(20) NOT NULL DEFAULT 'html',
    content LONGTEXT NOT NULL,
    status ENUM('queued','active','paused','completed','cancelled','failed') NOT NULL DEFAULT 'queued',
    auto_continue TINYINT(1) NOT NULL DEFAULT 1,
    total_recipients INT UNSIGNED NOT NULL DEFAULT 0,
    dispatched_recipients INT UNSIGNED NOT NULL DEFAULT 0,
    blocked_recipients INT UNSIGNED NOT NULL DEFAULT 0,
    failed_recipients INT UNSIGNED NOT NULL DEFAULT 0,
    last_error VARCHAR(500) NULL,
    created_by BIGINT UNSIGNED NULL,
    completed_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_sender_campaign_runs_status (status, auto_continue, id),
    KEY idx_sender_campaign_runs_source (source_campaign_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sender_campaign_recipients (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT UNSIGNED NOT NULL,
    newsletter_subscriber_id BIGINT UNSIGNED NULL,
    recipient_email VARCHAR(190) NOT NULL,
    recipient_name VARCHAR(190) NULL,
    status ENUM('queued','processing','dispatched','blocked','failed') NOT NULL DEFAULT 'queued',
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME NULL,
    validation_status VARCHAR(20) NULL,
    validation_reason VARCHAR(255) NULL,
    validation_checked_at DATETIME NULL,
    batch_id BIGINT UNSIGNED NULL,
    last_error VARCHAR(500) NULL,
    dispatched_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_sender_campaign_recipient (run_id, recipient_email),
    KEY idx_sender_campaign_recipient_ready (run_id, status, next_attempt_at, id),
    KEY idx_sender_campaign_recipient_batch (batch_id),
    KEY idx_sender_campaign_recipient_dispatched (dispatched_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sender_campaign_batches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT UNSIGNED NOT NULL,
    batch_no INT UNSIGNED NOT NULL,
    group_title VARCHAR(255) NOT NULL,
    provider_group_id VARCHAR(100) NULL,
    provider_campaign_id VARCHAR(100) NULL,
    recipient_count INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('preparing','sent','failed') NOT NULL DEFAULT 'preparing',
    last_error VARCHAR(500) NULL,
    sent_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_sender_campaign_batch_no (run_id, batch_no),
    KEY idx_sender_campaign_batch_sent (sent_at),
    KEY idx_sender_campaign_batch_status (status, run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
